### ISSUE TITLE
Could not find a declaration file for module 'cp-react-tree-table'.

### ISSUE THREAD

**Issue by jgeluk** [constantin-p/cp-react-tree-table#13]
Getting an error like:

```
Could not find a declaration file for module 'cp-react-tree-table'. './node_modules/cp-react-tree-table/dist/index.js' implicitly has an 'any' type.
  Try `npm install @types/cp-react-tree-table` if it exists or add a new declaration (.d.ts) file containing `declare module 'cp-react-tree-table';`ts(7016)
```

On the import statement (as copied from the example)

**Comment by constantin-p** [comment]
Hi @jgeluk,

From the error message, I assume that you are using the library in a TypeScript project. The current version (v0.x) is not using TypeScript for type-checking so the TypeScript compiler is **not** going to find any type definitions associated with the module.

You can solve the TypeScript error by creating a type declaration file `cp-react-tree-table.d.ts` with the following content:
```
declare module 'cp-react-tree-table';
```


**NOTE:** If you are interested in out of the box support for TypeScript, [the next version](https://github.com/constantin-p/cp-react-tree-table/pull/11) (v1.0) is written in TypeScript and it is going to be released in a few weeks.

**Comment by altavir** [comment]
No d.ts yet. Even if the project is written in TypeScript.

**Comment by constantin-p** [comment]
You are right, @altavir. I'm going to change the build process to generate the definition files in the next few days.

**Comment by altavir** [comment]
OK, I've even painfully reproduced the build (Kotlin-JS, completely unfamiliar with JS/TS stack), but it gives type error.

**Comment by constantin-p** [comment]
Hi @altavir,

Commit d5ce84e3388b5ce42514efab348e1a3c9ecde3f1 (npm: [`1.0.0-beta.6`](https://www.npmjs.com/package/cp-react-tree-table/v/1.0.0-beta.6)) should fix this issue by generating a declaration file at build time.

**Comment by altavir** [comment]
Thanks, I've already created manual bindings for kotlin, but I will check it later.
