### ISSUE TITLE
table data is not updating even though new data is set dynamically.

### ISSUE THREAD

**Issue by raghavendraguptathunguntla** [constantin-p/cp-react-tree-table#14]
When will the udpated version of this tree will be available on Git hub repo?

**Comment by constantin-p** [comment]
Hi @raghavendraguptathunguntla,

If you are referring to the [exp/tree-node-update](https://github.com/constantin-p/cp-react-tree-table/tree/exp/tree-node-update) branch, it was just an experiment which will not be merged into the master branch. Instead, [v1.0](https://github.com/constantin-p/cp-react-tree-table/pull/11) will support this functionality among other features.

The only remaining task before release is finishing up the documentation, so you should expect a new version by the end of next week.
