### ISSUE TITLE
hasVisibleChildren on RowMetadata for v1.0 

### ISSUE THREAD

**Issue by ChristineDu** [constantin-p/cp-react-tree-table#15]
Hi,

I noticed that in v1.0 hasVisibleChildren has been removed from RowMetadata properties. Is there other substitutes for this property? Basically what I'm trying to achieve is to show different toggle icon when the node is expanded.

Thanks!

**Comment by constantin-p** [comment]
Hi @ChristineDu,

You are right, v1.0 has no equivalent of `hasVisibleChildren` at the moment. Towards the end of next week I'm going to implement this functionality.

**Comment by thinkle-iacs** [comment]
Any update on the visible children functionality?

**Comment by constantin-p** [comment]
@thinkle-iacs I need to spend a few hours to implement it, but unfortunately my schedule is pretty full. I'm going to see if I can take a look at it during the next few weekends but I'm not promising anything.

**Comment by gax97** [comment]
Any update on this?

**Comment by constantin-p** [comment]
The latest version [(npm: v1.0.0-beta.9)](https://www.npmjs.com/package/cp-react-tree-table/v/1.0.0-beta.9) introduces [__`isExpanded`__](https://constantin.software/cp-react-tree-table/docs/#v1_0_api-reference_row-state) as a property on the `RowState` object, which means that the expanded/collapsed state of a node can now be accessed inside the cell renderer through `row.$state.isExpanded`.

[Demo](https://constantin-p.github.io/cp-react-tree-table/) | [JSFiddle](http://jsfiddle.net/constantin_p/hb8597sr/)
