### ISSUE TITLE
Can i use it with React 15.2 version?

### ISSUE THREAD

**Issue by rathnamvemula** [constantin-p/cp-react-tree-table#16]
Hi,
I am using React JS 15.x version. How can I use this component in React JS app i.e using 15.2 version?

**Comment by constantin-p** [comment]
Hi

Commit a98d6841956f338c6ce9ff66ac562ea6d3a2a725 (npm: [`v1.0.0-beta.4`](https://www.npmjs.com/package/cp-react-tree-table/v/1.0.0-beta.4)) should fix all compatibility issues for React v15.0.

The demo/examples should work for React `v15.0` with the following exceptions:
- __React.Fragment__ is not available (use a div or other component as a wrapper)
- __React.createRef()__ is not available, https://github.com/constantin-p/cp-react-tree-table/pull/5#issue-201645080 has a short example of how to acquire a reference in `v15.0`

**Comment by rathnamvemula** [comment]
That's Great. Thanks for immediately fixing and publishing the new version. When will be the official release of v1.0.0?

**Comment by constantin-p** [comment]
At this point https://github.com/constantin-p/cp-react-tree-table/issues/15 is the only blocking issue. I'm going to try to work on implementing it in the next few weeks, but right now I cannot give an exact date for when __`v1.0`__ will be ready.
