### ISSUE TITLE
hasVisibleChildren not available in v1.0.0-beta.8

### ISSUE THREAD

**Issue by praveennetcity** [constantin-p/cp-react-tree-table#19]
Hi,

I am using  v1.0.0-beta.8,  hasVisibleChildren is not available RowMetadata properties. Is there any alternative for this property. I am trying to show toggle icons on expand/ collapse

Thanks!

**Comment by constantin-p** [comment]
Same as https://github.com/constantin-p/cp-react-tree-table/issues/15

__`v1.0-X`__ has no equivalent of `hasVisibleChildren` at the moment.
