### ISSUE TITLE
Expose `onScoll` event

### ISSUE THREAD

**Issue by pmilla1606** [constantin-p/cp-react-tree-table#2]
It would be great to have access to the current scroll position from VirtualList.

**Comment by pmilla1606** [comment]
After clarification in #1 I will try to tackle this as well as a `scrollTo(node)` which is a feature I need

**Comment by constantin-p** [comment]
I added flow type definitions & documentation for #3  and merge it.
Regarding `scrollTo(node)`, at the beginning of the next week, I'm going to implement it.

**Comment by constantin-p** [comment]
I just opened #5  with an implementation for `scrollIntoView(node)` & `scrollTo(posY)`

I'm gonna close this issue because the original suggestion has been implemented. Check the pull request for discussing the new functionality.
