### ISSUE TITLE
Scroll to specific node  Highlighting

### ISSUE THREAD

**Issue by praveennetcity** [constantin-p/cp-react-tree-table#20]
I have implemented a search functionality, by using scroll to specific node option by the below example
https://jsfiddle.net/constantin_p/bksfxe61/11/?utm_source=website&utm_medium=embed&utm_campaign=bksfxe61

is there any parameter/option for **highlighting** the specific node (row) in the table when using scroll to specific node.

**Comment by constantin-p** [comment]
The library defers the job of rendering cells to the consumer code - you can provide a custom flag property in the tree data and use it in the cell renderer to dictate whether they should apply style/layout changes to highlight the corresponding row.  

```ts
const MOCK_DATA = [
  ...
  {
    data: { name: 'Company I', expenses: '105,000' },
    children: [
      { 
        data: { name: 'Department 1', expenses: '75,000', isHighlighted: true },
      },
      ...
    ]
  },
  ...
];
```
```tsx
<TreeTable
  value={treeValue}
  onChange={this.handleOnChange}>

  <TreeTable.Column
    renderCell={(row) => <span className={row.data.isHighlighted ? "highlight" : ""}>{row.data.name}</span>}
    renderHeaderCell={() => <span>Name</span>}/>
  ...
</TreeTable>
```
