### ISSUE TITLE
Nesting levels gets hidden when there are more nesting levels

### ISSUE THREAD

**Issue by praveennetcity** [constantin-p/cp-react-tree-table#22]
When you have multiple nesting levels the nesting levels is getting hidden 

I have nesting level till ten but i am not able to see more than 4

https://jsfiddle.net/praveenc36/ya4cuwxb/2/

<img width="568" alt="Screen Shot 2019-12-10 at 9 29 28 AM" src="https://user-images.githubusercontent.com/7857560/70493996-a7bfd000-1b2f-11ea-933b-93dab770484c.png">

**Comment by zoness32** [comment]
I'm pretty sure you'll need to widen the size of your Name column, and probably want to increase the height of your rows so the text is visible when it wraps. Though widening your Name column will also prevent wrapping, so the height might not be an issue. This can be done via CSS.
