### ISSUE TITLE
Updating children after row expand

### ISSUE THREAD

**Issue by anupalhub** [constantin-p/cp-react-tree-table#23]
Hi,

How can we update the table after the state change. 
I am updating the state with children of selected row on click. But the table not get update with new children underneath that row. 

Can we achieve in the current version?

**Comment by thekennysong** [comment]
+1

**Comment by rachita18144** [comment]
@anupalhub you can update the data as well as it's children in your original array and render the entire data using `TreeState.create()`. However, I couldn't find anyway to update the children without re-rendering the entire table state. 
Is there any way to do that or if that functionality is not there, is there any plan to implement it ?
