### ISSUE TITLE
HasChildrenVisible from v0.* removed in v1

### ISSUE THREAD

**Issue by robmim** [constantin-p/cp-react-tree-table#28]
Is there any way to know if a row has children visible in v1 ?

I want to boost the ui/ux  by changing this black triangle used to mark rows with childrens but i'm stock simply because i can't know if it is expanded or not. 

Am i missing something ?

**Comment by robmim** [comment]
Implementing ARIA in this component would be a great feature. You can check Table Tree from atlaskit for example. Using aria-expanded="true/false" this way i could at least style the button based on the attribute value. ;)

https://atlaskit.atlassian.com/packages/design-system/table-tree

We can't use this component from Atlaskit because of performance issues. Having this feature on your would be awesome.

**Comment by constantin-p** [comment]
Hi @robmim,

I've just released a [new version](https://www.npmjs.com/package/cp-react-tree-table/v/1.0.0-beta.9) which introduces [__`isExpanded`__](https://constantin.software/cp-react-tree-table/docs/#v1_0_api-reference_row-state) as a property on the `RowState` object.

You can now access the expanded/collapsed state of a node inside the cell renderer through `row.$state.isExpanded`:

```js
  ...

  renderCell = (row) => {
    return (
      <button
        onClick={row.toggleChildren}
        disabled={!row.metadata.hasChildren}>

        {row.$state.isExpanded ? '-' : '+'}
        {row.data.name}
      </button>
    );
  }

  ...
```

You can take a look at [this JSFiddle](http://jsfiddle.net/constantin_p/hb8597sr/) for a full demo.

**Comment by robmim** [comment]
I can't thank you enough. This little piece of code give so much more value to your component. Great job by the way ;)
