### ISSUE TITLE
Enhancement : Make column sortable

### ISSUE THREAD

**Issue by robmim** [constantin-p/cp-react-tree-table#30]
Hy CP,

I really don't know how long this feature would take to implement but having the possibility to sort the columns on the header click would be another great feature on this component. 

Maybe this could be a good starting point for this feature
https://www.smashingmagazine.com/2020/03/sortable-tables-react/

**Comment by constantin-p** [comment]
Sorting/filtering or any other data manipulation operations can be achieved externally by updating the [__`TreeState`__](https://constantin.software/cp-react-tree-table/docs/#v1_0_api-reference_tree-state) value provided to `TreeTable.
