### ISSUE TITLE
Dynamic table height

### ISSUE THREAD

**Issue by highthamok** [constantin-p/cp-react-tree-table#35]
Hello! 

I have a question, If my data that I want to display isn't much, can I make the height of the table changes dynamically with the volume of the data ? 

![image](https://user-images.githubusercontent.com/72567864/95483576-4eab0d80-0987-11eb-91b7-d430071158ad.png)

like in this case, is it possible to make the height of the table according to the size of the data ? 

Thank you

**Comment by constantin-p** [comment]
The height of the rendered table can be dynamically updated through the `height` property on the [`TreeTable`](https://constantin.software/cp-react-tree-table/docs/#v1_0_api-reference_tree-table) component.
