### ISSUE TITLE
React 18.2.0 Support?

### ISSUE THREAD

**Issue by b0arderman** [constantin-p/cp-react-tree-table#47]
I'm receiving the following error when attempting to install the package.  Has cp-react-tree-table been tested with react@18.2.0?  Would it be possible to update the component for the dependency with react@18.2.0?
Thanks,
Eric

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: mb_enhanced_dashboards2@0.1.0
npm ERR! Found: react@18.2.0
npm ERR! node_modules/react
npm ERR!   react@"^18.1.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^0.14.9 || ^15.0.0 || ^16.0.0 || ^17.0.0" from cp-react-tree-table@1.0.0-beta.13
npm ERR! node_modules/cp-react-tree-table
npm ERR!   cp-react-tree-table@"*" from the root project

**Comment by constantin-p** [comment]
Hi @b0arderman, version [`v1.1.0`](https://www.npmjs.com/package/cp-react-tree-table/v/1.1.0) has just been released which includes support for React 18.
