### ISSUE TITLE
Issue with scrollIntoView

### ISSUE THREAD

**Issue by felipefaraco** [constantin-p/cp-react-tree-table#6]
Hi,

I found an issue with your demo (https://jsfiddle.net/constantin_p/fvuswrbm/), reproduced both on Chrome and FF. Steps: 

1 Un-toggle both [depth:2](row:14) and [depth:1](row:13)
2 Scroll up to the top of the list
3 Click the button "Scroll to ..."
4 Notice how it only scrolls to [depth:2](row:15) 
(it does expand [depth:3](row:15), but won't scroll to that position)

**Comment by constantin-p** [comment]
Hi @felipefaraco,

Thanks for your bug report. I can reproduce the issue and I'm gonna push a fix later this week.

**Comment by constantin-p** [comment]
[v0.5.1](https://www.npmjs.com/package/cp-react-tree-table/v/0.5.1) (commit b81251a56f89df5ab150cba0980e4d9e4b63ac43) should contain the fix for the described issue. @felipefaraco let me know if everything works on your end.

**Comment by felipefaraco** [comment]
Just tested, works great! Thank you for doing this, I really like your library, suits my data very well! 👍
