### ISSUE TITLE
Toggle Icon on expand / collapse

### ISSUE THREAD

**Issue by SujaiRaj** [constantin-p/cp-react-tree-table#7]
https://jsfiddle.net/5yvgbrtk/

Am trying to modify the [toggle] into interactive  + / - icons , based on node expanded / collapsed.
Since am using click event, the icons doesn't work as intended when multi-levels are closed at the same time.

Is there a method that could let us know, if the Node's Descendants are displayed in the DOM or not.

Any help would be much appreciated. Thanks.

**Comment by constantin-p** [comment]
Hi @SujaiRaj,

Right now the API doesn't share the (collapsed/expanded) state of a node, but I'm gonna take care of this issue this weekend.

**Comment by constantin-p** [comment]
Hi,

I added a new field to the row's metadata object ([`hasVisibleChildren`](https://github.com/constantin-p/cp-react-tree-table/blob/2b6fca698b4ea1e19e4866f2608c21655c8a97b4/README.md#props)) that should allow you to implement the functionality you're looking for.

This feature has been introduced by commit 048186ead859b600e6ad1276ec9ee1e2cbfb0cc0 and is available to use in [v0.6.0](https://www.npmjs.com/package/cp-react-tree-table/v/0.6.0). 

Here is an example that is based on your JSFiddle link (https://jsfiddle.net/constantin_p/Lystd2j9/).

**Comment by SujaiRaj** [comment]
Hi @constantin-p ,
Thanks a lot !!!  You saved the day . I really owe you one.  👍 

BTW, I tweaked the styling a bit to animate the arrows. You could utilize it if it is good.
https://jsfiddle.net/sujaikarthik/Lystd2j9/17/
